// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netComm.proto

package gcpb;

public final class NetComm {
  private NetComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartBeatReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    boolean hasTs();
    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    long getTs();
  }
  /**
   * Protobuf type {@code HeartBeatReq}
   *
   * <pre>
   *心跳请求
   * </pre>
   */
  public static final class HeartBeatReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeatReq)
      HeartBeatReqOrBuilder {
    // Use HeartBeatReq.newBuilder() to construct.
    private HeartBeatReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatReq defaultInstance;
    public static HeartBeatReq getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ts_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gcpb.NetComm.internal_static_HeartBeatReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gcpb.NetComm.internal_static_HeartBeatReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gcpb.NetComm.HeartBeatReq.class, gcpb.NetComm.HeartBeatReq.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatReq> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatReq>() {
      public HeartBeatReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    public long getTs() {
      return ts_;
    }

    private void initFields() {
      ts_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, ts_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, ts_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gcpb.NetComm.HeartBeatReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gcpb.NetComm.HeartBeatReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gcpb.NetComm.HeartBeatReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gcpb.NetComm.HeartBeatReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatReq}
     *
     * <pre>
     *心跳请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatReq)
        gcpb.NetComm.HeartBeatReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gcpb.NetComm.internal_static_HeartBeatReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gcpb.NetComm.internal_static_HeartBeatReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gcpb.NetComm.HeartBeatReq.class, gcpb.NetComm.HeartBeatReq.Builder.class);
      }

      // Construct using gcpb.NetComm.HeartBeatReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gcpb.NetComm.internal_static_HeartBeatReq_descriptor;
      }

      public gcpb.NetComm.HeartBeatReq getDefaultInstanceForType() {
        return gcpb.NetComm.HeartBeatReq.getDefaultInstance();
      }

      public gcpb.NetComm.HeartBeatReq build() {
        gcpb.NetComm.HeartBeatReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gcpb.NetComm.HeartBeatReq buildPartial() {
        gcpb.NetComm.HeartBeatReq result = new gcpb.NetComm.HeartBeatReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gcpb.NetComm.HeartBeatReq) {
          return mergeFrom((gcpb.NetComm.HeartBeatReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gcpb.NetComm.HeartBeatReq other) {
        if (other == gcpb.NetComm.HeartBeatReq.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gcpb.NetComm.HeartBeatReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gcpb.NetComm.HeartBeatReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long ts_ ;
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatReq)
    }

    static {
      defaultInstance = new HeartBeatReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeatReq)
  }

  public interface HeartBeatRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    boolean hasTs();
    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    long getTs();
  }
  /**
   * Protobuf type {@code HeartBeatRsp}
   *
   * <pre>
   *心跳响应
   * </pre>
   */
  public static final class HeartBeatRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeatRsp)
      HeartBeatRspOrBuilder {
    // Use HeartBeatRsp.newBuilder() to construct.
    private HeartBeatRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatRsp defaultInstance;
    public static HeartBeatRsp getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ts_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gcpb.NetComm.internal_static_HeartBeatRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gcpb.NetComm.internal_static_HeartBeatRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gcpb.NetComm.HeartBeatRsp.class, gcpb.NetComm.HeartBeatRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatRsp> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatRsp>() {
      public HeartBeatRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 ts = 1;</code>
     *
     * <pre>
     *时间戳.
     * </pre>
     */
    public long getTs() {
      return ts_;
    }

    private void initFields() {
      ts_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, ts_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, ts_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gcpb.NetComm.HeartBeatRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gcpb.NetComm.HeartBeatRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gcpb.NetComm.HeartBeatRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gcpb.NetComm.HeartBeatRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatRsp}
     *
     * <pre>
     *心跳响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatRsp)
        gcpb.NetComm.HeartBeatRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gcpb.NetComm.internal_static_HeartBeatRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gcpb.NetComm.internal_static_HeartBeatRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gcpb.NetComm.HeartBeatRsp.class, gcpb.NetComm.HeartBeatRsp.Builder.class);
      }

      // Construct using gcpb.NetComm.HeartBeatRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gcpb.NetComm.internal_static_HeartBeatRsp_descriptor;
      }

      public gcpb.NetComm.HeartBeatRsp getDefaultInstanceForType() {
        return gcpb.NetComm.HeartBeatRsp.getDefaultInstance();
      }

      public gcpb.NetComm.HeartBeatRsp build() {
        gcpb.NetComm.HeartBeatRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gcpb.NetComm.HeartBeatRsp buildPartial() {
        gcpb.NetComm.HeartBeatRsp result = new gcpb.NetComm.HeartBeatRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gcpb.NetComm.HeartBeatRsp) {
          return mergeFrom((gcpb.NetComm.HeartBeatRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gcpb.NetComm.HeartBeatRsp other) {
        if (other == gcpb.NetComm.HeartBeatRsp.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gcpb.NetComm.HeartBeatRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gcpb.NetComm.HeartBeatRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long ts_ ;
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 ts = 1;</code>
       *
       * <pre>
       *时间戳.
       * </pre>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatRsp)
    }

    static {
      defaultInstance = new HeartBeatRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeatRsp)
  }

  public interface HostPortOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HostPort)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string host = 1;</code>
     *
     * <pre>
     *主机.
     * </pre>
     */
    boolean hasHost();
    /**
     * <code>required string host = 1;</code>
     *
     * <pre>
     *主机.
     * </pre>
     */
    java.lang.String getHost();
    /**
     * <code>required string host = 1;</code>
     *
     * <pre>
     *主机.
     * </pre>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>required uint32 port = 2;</code>
     *
     * <pre>
     *端口.
     * </pre>
     */
    boolean hasPort();
    /**
     * <code>required uint32 port = 2;</code>
     *
     * <pre>
     *端口.
     * </pre>
     */
    int getPort();

    /**
     * <code>required uint32 stat = 3;</code>
     *
     * <pre>
     *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
     * </pre>
     */
    boolean hasStat();
    /**
     * <code>required uint32 stat = 3;</code>
     *
     * <pre>
     *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
     * </pre>
     */
    int getStat();

    /**
     * <code>required string desc = 4;</code>
     *
     * <pre>
     *描述.
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 4;</code>
     *
     * <pre>
     *描述.
     * </pre>
     */
    java.lang.String getDesc();
    /**
     * <code>required string desc = 4;</code>
     *
     * <pre>
     *描述.
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>required uint32 indx = 5;</code>
     *
     * <pre>
     *索引.
     * </pre>
     */
    boolean hasIndx();
    /**
     * <code>required uint32 indx = 5;</code>
     *
     * <pre>
     *索引.
     * </pre>
     */
    int getIndx();
  }
  /**
   * Protobuf type {@code HostPort}
   *
   * <pre>
   *主机与端口.
   * </pre>
   */
  public static final class HostPort extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HostPort)
      HostPortOrBuilder {
    // Use HostPort.newBuilder() to construct.
    private HostPort(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HostPort(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HostPort defaultInstance;
    public static HostPort getDefaultInstance() {
      return defaultInstance;
    }

    public HostPort getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HostPort(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              host_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              stat_ = input.readUInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              desc_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              indx_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gcpb.NetComm.internal_static_HostPort_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gcpb.NetComm.internal_static_HostPort_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gcpb.NetComm.HostPort.class, gcpb.NetComm.HostPort.Builder.class);
    }

    public static com.google.protobuf.Parser<HostPort> PARSER =
        new com.google.protobuf.AbstractParser<HostPort>() {
      public HostPort parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HostPort(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HostPort> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HOST_FIELD_NUMBER = 1;
    private java.lang.Object host_;
    /**
     * <code>required string host = 1;</code>
     *
     * <pre>
     *主机.
     * </pre>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string host = 1;</code>
     *
     * <pre>
     *主机.
     * </pre>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 1;</code>
     *
     * <pre>
     *主机.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required uint32 port = 2;</code>
     *
     * <pre>
     *端口.
     * </pre>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 port = 2;</code>
     *
     * <pre>
     *端口.
     * </pre>
     */
    public int getPort() {
      return port_;
    }

    public static final int STAT_FIELD_NUMBER = 3;
    private int stat_;
    /**
     * <code>required uint32 stat = 3;</code>
     *
     * <pre>
     *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
     * </pre>
     */
    public boolean hasStat() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 stat = 3;</code>
     *
     * <pre>
     *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
     * </pre>
     */
    public int getStat() {
      return stat_;
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private java.lang.Object desc_;
    /**
     * <code>required string desc = 4;</code>
     *
     * <pre>
     *描述.
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string desc = 4;</code>
     *
     * <pre>
     *描述.
     * </pre>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 4;</code>
     *
     * <pre>
     *描述.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDX_FIELD_NUMBER = 5;
    private int indx_;
    /**
     * <code>required uint32 indx = 5;</code>
     *
     * <pre>
     *索引.
     * </pre>
     */
    public boolean hasIndx() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 indx = 5;</code>
     *
     * <pre>
     *索引.
     * </pre>
     */
    public int getIndx() {
      return indx_;
    }

    private void initFields() {
      host_ = "";
      port_ = 0;
      stat_ = 0;
      desc_ = "";
      indx_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, stat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, indx_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, stat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDescBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, indx_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gcpb.NetComm.HostPort parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gcpb.NetComm.HostPort parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gcpb.NetComm.HostPort parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gcpb.NetComm.HostPort parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gcpb.NetComm.HostPort parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gcpb.NetComm.HostPort parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gcpb.NetComm.HostPort parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gcpb.NetComm.HostPort parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gcpb.NetComm.HostPort parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gcpb.NetComm.HostPort parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gcpb.NetComm.HostPort prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HostPort}
     *
     * <pre>
     *主机与端口.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HostPort)
        gcpb.NetComm.HostPortOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gcpb.NetComm.internal_static_HostPort_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gcpb.NetComm.internal_static_HostPort_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gcpb.NetComm.HostPort.class, gcpb.NetComm.HostPort.Builder.class);
      }

      // Construct using gcpb.NetComm.HostPort.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        stat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        indx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gcpb.NetComm.internal_static_HostPort_descriptor;
      }

      public gcpb.NetComm.HostPort getDefaultInstanceForType() {
        return gcpb.NetComm.HostPort.getDefaultInstance();
      }

      public gcpb.NetComm.HostPort build() {
        gcpb.NetComm.HostPort result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gcpb.NetComm.HostPort buildPartial() {
        gcpb.NetComm.HostPort result = new gcpb.NetComm.HostPort(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stat_ = stat_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.indx_ = indx_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gcpb.NetComm.HostPort) {
          return mergeFrom((gcpb.NetComm.HostPort)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gcpb.NetComm.HostPort other) {
        if (other == gcpb.NetComm.HostPort.getDefaultInstance()) return this;
        if (other.hasHost()) {
          bitField0_ |= 0x00000001;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasStat()) {
          setStat(other.getStat());
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000008;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasIndx()) {
          setIndx(other.getIndx());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHost()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasStat()) {
          
          return false;
        }
        if (!hasDesc()) {
          
          return false;
        }
        if (!hasIndx()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gcpb.NetComm.HostPort parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gcpb.NetComm.HostPort) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object host_ = "";
      /**
       * <code>required string host = 1;</code>
       *
       * <pre>
       *主机.
       * </pre>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string host = 1;</code>
       *
       * <pre>
       *主机.
       * </pre>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string host = 1;</code>
       *
       * <pre>
       *主机.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 1;</code>
       *
       * <pre>
       *主机.
       * </pre>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 1;</code>
       *
       * <pre>
       *主机.
       * </pre>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 1;</code>
       *
       * <pre>
       *主机.
       * </pre>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required uint32 port = 2;</code>
       *
       * <pre>
       *端口.
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 port = 2;</code>
       *
       * <pre>
       *端口.
       * </pre>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required uint32 port = 2;</code>
       *
       * <pre>
       *端口.
       * </pre>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 port = 2;</code>
       *
       * <pre>
       *端口.
       * </pre>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      private int stat_ ;
      /**
       * <code>required uint32 stat = 3;</code>
       *
       * <pre>
       *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
       * </pre>
       */
      public boolean hasStat() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 stat = 3;</code>
       *
       * <pre>
       *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
       * </pre>
       */
      public int getStat() {
        return stat_;
      }
      /**
       * <code>required uint32 stat = 3;</code>
       *
       * <pre>
       *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
       * </pre>
       */
      public Builder setStat(int value) {
        bitField0_ |= 0x00000004;
        stat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 stat = 3;</code>
       *
       * <pre>
       *状态(0: 正常, 1: 新区, 2: 维护中, 3: 隐藏(客户端不可见)).
       * </pre>
       */
      public Builder clearStat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stat_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>required string desc = 4;</code>
       *
       * <pre>
       *描述.
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string desc = 4;</code>
       *
       * <pre>
       *描述.
       * </pre>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string desc = 4;</code>
       *
       * <pre>
       *描述.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 4;</code>
       *
       * <pre>
       *描述.
       * </pre>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 4;</code>
       *
       * <pre>
       *描述.
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 4;</code>
       *
       * <pre>
       *描述.
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        desc_ = value;
        onChanged();
        return this;
      }

      private int indx_ ;
      /**
       * <code>required uint32 indx = 5;</code>
       *
       * <pre>
       *索引.
       * </pre>
       */
      public boolean hasIndx() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 indx = 5;</code>
       *
       * <pre>
       *索引.
       * </pre>
       */
      public int getIndx() {
        return indx_;
      }
      /**
       * <code>required uint32 indx = 5;</code>
       *
       * <pre>
       *索引.
       * </pre>
       */
      public Builder setIndx(int value) {
        bitField0_ |= 0x00000010;
        indx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 indx = 5;</code>
       *
       * <pre>
       *索引.
       * </pre>
       */
      public Builder clearIndx() {
        bitField0_ = (bitField0_ & ~0x00000010);
        indx_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HostPort)
    }

    static {
      defaultInstance = new HostPort(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HostPort)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeatReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeatRsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HostPort_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HostPort_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnetComm.proto\"\032\n\014HeartBeatReq\022\n\n\002ts\030\001 " +
      "\002(\004\"\032\n\014HeartBeatRsp\022\n\n\002ts\030\001 \002(\004\"P\n\010HostP" +
      "ort\022\014\n\004host\030\001 \002(\t\022\014\n\004port\030\002 \002(\r\022\014\n\004stat\030" +
      "\003 \002(\r\022\014\n\004desc\030\004 \002(\t\022\014\n\004indx\030\005 \002(\rB\006\n\004gcp" +
      "b"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartBeatReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeatReq_descriptor,
        new java.lang.String[] { "Ts", });
    internal_static_HeartBeatRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeatRsp_descriptor,
        new java.lang.String[] { "Ts", });
    internal_static_HostPort_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HostPort_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HostPort_descriptor,
        new java.lang.String[] { "Host", "Port", "Stat", "Desc", "Indx", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
